export const brands=[
{id:'apple',slug:'apple',nameFa:'اپل',nameEn:'Apple',mark:'',tone:'apple',featured:true},{id:'samsung',slug:'samsung',nameFa:'سامسونگ',nameEn:'Samsung',mark:'S',tone:'samsung',featured:true},{id:'xiaomi',slug:'xiaomi',nameFa:'شیائومی',nameEn:'Xiaomi',mark:'mi',tone:'xiaomi',featured:true},{id:'google',slug:'google',nameFa:'گوگل',nameEn:'Google',mark:'G',tone:'google',featured:true},{id:'honor',slug:'honor',nameFa:'آنر',nameEn:'HONOR',mark:'H',tone:'honor',featured:true},{id:'oneplus',slug:'oneplus',nameFa:'وان‌پلاس',nameEn:'OnePlus',mark:'1+',tone:'oneplus',featured:true},{id:'nothing',slug:'nothing',nameFa:'ناتینگ',nameEn:'Nothing',mark:'N',tone:'nothing',featured:true},{id:'motorola',slug:'motorola',nameFa:'موتورولا',nameEn:'Motorola',mark:'M',tone:'motorola',featured:true},
{id:'sony',slug:'sony',nameFa:'سونی',nameEn:'Sony',mark:'S',tone:'plain'},{id:'huawei',slug:'huawei',nameFa:'هواوی',nameEn:'Huawei',mark:'H',tone:'plain'},{id:'oppo',slug:'oppo',nameFa:'اوپو',nameEn:'OPPO',mark:'O',tone:'plain'},{id:'vivo',slug:'vivo',nameFa:'ویوو',nameEn:'vivo',mark:'V',tone:'plain'}];
export const categories=[{id:'phones',slug:'phones',name:'گوشی موبایل',note:'پرچمدار تا اقتصادی'},{id:'tablets',slug:'tablets',name:'تبلت',note:'کار و سرگرمی'},{id:'wearables',slug:'wearables',name:'ساعت هوشمند',note:'پوشیدنی‌های هوشمند'},{id:'audio',slug:'audio',name:'هدفون و صدا',note:'اکوسیستم صوتی'},{id:'accessories',slug:'accessories',name:'لوازم جانبی',note:'کامل‌کننده تجربه'}];
export const series=[
{id:'iphone',slug:'iphone',brandId:'apple',nameFa:'آیفون',nameEn:'iPhone',description:'خانواده اصلی آیفون.'},{id:'galaxy-s',slug:'galaxy-s',brandId:'samsung',nameFa:'گلکسی S',nameEn:'Galaxy S',description:'پرچمدارهای Galaxy S.'},{id:'galaxy-z',slug:'galaxy-z',brandId:'samsung',nameFa:'گلکسی Z',nameEn:'Galaxy Z',description:'گوشی‌های تاشوی Galaxy.'},{id:'xiaomi-number',slug:'xiaomi-number',brandId:'xiaomi',nameFa:'سری عددی شیائومی',nameEn:'Xiaomi Number',description:'رده بالای شیائومی.'},{id:'redmi-note',slug:'redmi-note',brandId:'xiaomi',nameFa:'ردمی نوت',nameEn:'Redmi Note',description:'تعادل قیمت و امکانات.'},{id:'pixel',slug:'pixel',brandId:'google',nameFa:'پیکسل',nameEn:'Pixel',description:'خانواده Google Pixel.'},{id:'magic',slug:'magic',brandId:'honor',nameFa:'مجیک',nameEn:'Magic',description:'پرچمدارهای HONOR.'},{id:'oneplus',slug:'oneplus',brandId:'oneplus',nameFa:'وان‌پلاس',nameEn:'OnePlus',description:'پرچمدارهای OnePlus.'}];
export const models=[
{id:'iphone-17-pro-max',slug:'iphone-17-pro-max',brandId:'apple',seriesId:'iphone',nameFa:'آیفون ۱۷ پرو مکس',nameEn:'iPhone 17 Pro Max',rating:4.9,reviews:184,specs:{display:'6.9″ OLED',camera:'48MP Pro',chip:'A19 Pro',battery:'تا 33 ساعت'}},
{id:'iphone-17-pro',slug:'iphone-17-pro',brandId:'apple',seriesId:'iphone',nameFa:'آیفون ۱۷ پرو',nameEn:'iPhone 17 Pro',rating:4.8,reviews:123,specs:{display:'6.3″ OLED',camera:'48MP Pro',chip:'A19 Pro',battery:'تا 27 ساعت'}},
{id:'iphone-17',slug:'iphone-17',brandId:'apple',seriesId:'iphone',nameFa:'آیفون ۱۷',nameEn:'iPhone 17',rating:4.7,reviews:201,specs:{display:'6.3″ OLED',camera:'48MP Dual',chip:'A19',battery:'تا 30 ساعت'}},
{id:'s26-ultra',slug:'galaxy-s26-ultra',brandId:'samsung',seriesId:'galaxy-s',nameFa:'گلکسی S26 اولترا',nameEn:'Galaxy S26 Ultra',rating:4.8,reviews:167,specs:{display:'6.9″ AMOLED',camera:'200MP',chip:'Snapdragon Elite',battery:'5000mAh'}},
{id:'s26-plus',slug:'galaxy-s26-plus',brandId:'samsung',seriesId:'galaxy-s',nameFa:'گلکسی S26 پلاس',nameEn:'Galaxy S26+',rating:4.7,reviews:91,specs:{display:'6.7″ AMOLED',camera:'50MP Triple',chip:'Snapdragon Elite',battery:'4900mAh'}},
{id:'fold7',slug:'galaxy-z-fold-7',brandId:'samsung',seriesId:'galaxy-z',nameFa:'گلکسی Z Fold 7',nameEn:'Galaxy Z Fold 7',rating:4.7,reviews:78,specs:{display:'7.6″ Foldable',camera:'200MP',chip:'Snapdragon Elite',battery:'4400mAh'}},
{id:'x15-ultra',slug:'xiaomi-15-ultra',brandId:'xiaomi',seriesId:'xiaomi-number',nameFa:'شیائومی ۱۵ اولترا',nameEn:'Xiaomi 15 Ultra',rating:4.7,reviews:88,specs:{display:'6.73″ AMOLED',camera:'200MP Leica',chip:'Snapdragon Elite',battery:'5410mAh'}},
{id:'redmi-note-14',slug:'redmi-note-14-pro-plus',brandId:'xiaomi',seriesId:'redmi-note',nameFa:'ردمی نوت ۱۴ پرو پلاس',nameEn:'Redmi Note 14 Pro+',rating:4.6,reviews:140,specs:{display:'6.67″ AMOLED',camera:'200MP',chip:'Dimensity',battery:'5110mAh'}},
{id:'pixel-10-pro',slug:'pixel-10-pro',brandId:'google',seriesId:'pixel',nameFa:'پیکسل ۱۰ پرو',nameEn:'Pixel 10 Pro',rating:4.8,reviews:102,specs:{display:'6.3″ OLED',camera:'50MP Triple',chip:'Tensor',battery:'4870mAh'}},
{id:'magic7',slug:'honor-magic-7-pro',brandId:'honor',seriesId:'magic',nameFa:'آنر مجیک ۷ پرو',nameEn:'HONOR Magic7 Pro',rating:4.6,reviews:63,specs:{display:'6.8″ OLED',camera:'200MP',chip:'Snapdragon Elite',battery:'5850mAh'}},
{id:'oneplus13',slug:'oneplus-13',brandId:'oneplus',seriesId:'oneplus',nameFa:'وان‌پلاس ۱۳',nameEn:'OnePlus 13',rating:4.7,reviews:71,specs:{display:'6.82″ AMOLED',camera:'50MP Triple',chip:'Snapdragon Elite',battery:'6000mAh'}}];
export const colors=[{id:'black',nameFa:'مشکی',hex:'#121212'},{id:'white',nameFa:'سفید',hex:'#fafafa'},{id:'blue',nameFa:'آبی',hex:'#8fa7c0'},{id:'green',nameFa:'سبز',hex:'#9aac91'},{id:'gold',nameFa:'طلایی',hex:'#c9b389'},{id:'silver',nameFa:'نقره‌ای',hex:'#c7c9c9'},{id:'violet',nameFa:'بنفش',hex:'#a69abb'}];
function v(id,modelId,ram,storage,colorId,price,oldPrice=0,stock=8){return{id,modelId,ram,storage,colorId,price,oldPrice,stock,sku:`MX-${id.toUpperCase()}`,warranty:'۱۸ ماه گارانتی معتبر',delivery:'ارسال سریع ۱ تا ۲ روزه'}}
export const variants=[v('ip17pm-256-black','iphone-17-pro-max',12,256,'black',129900000,144900000,7),v('ip17pm-512-gold','iphone-17-pro-max',12,512,'gold',144900000,155900000,5),v('ip17pm-1tb-white','iphone-17-pro-max',12,1024,'white',168900000,0,3),v('ip17p-256-white','iphone-17-pro',12,256,'white',119900000,128900000,8),v('ip17-256-blue','iphone-17',8,256,'blue',89900000,94900000,9),v('s26u-512-black','s26-ultra',12,512,'black',99900000,107500000,6),v('s26u-1tb-violet','s26-ultra',16,1024,'violet',119900000,0,4),v('s26p-256-white','s26-plus',12,256,'white',83900000,90900000,7),v('fold7-512-silver','fold7',12,512,'silver',129900000,0,3),v('x15u-512-black','x15-ultra',16,512,'black',79800000,0,6),v('rn14-256-green','redmi-note-14',12,256,'green',42900000,46900000,11),v('p10p-256-blue','pixel-10-pro',16,256,'blue',72400000,76900000,5),v('m7p-512-black','magic7',12,512,'black',68900000,0,6),v('op13-512-green','oneplus13',16,512,'green',65900000,70900000,8)];
export const products=variants.map((x,i)=>{const m=models.find((z)=>z.id===x.modelId);return{...x,slug:x.id,titleFa:m?.nameFa||'گوشی موبایل',titleEn:m?.nameEn||'Mobile Phone',rating:m?.rating||4.5,reviews:m?.reviews||0,specs:m?.specs||{},isNew:i<5,isFeatured:i<8,categoryId:'phones'}});
export const shipping=[{id:'express',title:'ارسال سریع',detail:'۱ تا ۲ روز کاری',price:190000},{id:'standard',title:'ارسال عادی',detail:'۲ تا ۴ روز کاری',price:95000},{id:'pickup',title:'تحویل حضوری',detail:'رایگان',price:0}];
export const coupons=[{code:'WELCOME10',kind:'percent',value:10,min:50000000,max:3000000,label:'۱۰٪ تخفیف خوش‌آمدگویی'},{code:'MOBILEX1',kind:'fixed',value:1500000,min:70000000,max:1500000,label:'۱.۵ میلیون تومان تخفیف'}];
export const demoUser={id:'demo-user',name:'کاربر Mobilex',email:'demo@mobilex.local',phone:'۰۹۱۲۱۲۳۴۵۶۷'};
export const demoAddresses=[{id:'addr-1',title:'خانه',receiver:'کاربر Mobilex',phone:'۰۹۱۲۱۲۳۴۵۶۷',city:'تهران',detail:'خیابان نمونه، پلاک ۱۲، واحد ۳',postal:'1111111111',default:true},{id:'addr-2',title:'کار',receiver:'کاربر Mobilex',phone:'۰۹۱۲۱۲۳۴۵۶۷',city:'تهران',detail:'خیابان فناوری، ساختمان ۸',postal:'2222222222',default:false}];
export const demoOrders=[{id:'MX-20261001-0017',date:'امروز',status:'shipped',total:129900000,items:[{productId:'ip17pm-256-black',qty:1}],addressId:'addr-1',shippingId:'express',tracking:'MXTRK-817226'},{id:'MX-20260921-0009',date:'۳۰ شهریور',status:'delivered',total:83900000,items:[{productId:'s26p-256-white',qty:1}],addressId:'addr-2',shippingId:'standard',tracking:'MXTRK-441902'}];
export const statusMap={pending:{label:'در انتظار پرداخت',p:10},paid:{label:'پرداخت موفق',p:25},processing:{label:'در حال آماده‌سازی',p:50},shipped:{label:'در مسیر تحویل',p:78},delivered:{label:'تحویل داده شد',p:100},cancelled:{label:'لغو شده',p:0}};
export const guides=[{id:'budget',title:'با بودجه‌ام چه گوشی‌ای بخرم؟',text:'بودجه، نیاز و چند معیار اصلی را مشخص کن و بعد مدل‌ها را مقایسه کن.'},{id:'camera',title:'دوربین را چطور مقایسه کنم؟',text:'مگاپیکسل تنها معیار نیست؛ سنسور، لنز و پردازش را هم ببین.'},{id:'compare',title:'مقایسه درست چه شکلی است؟',text:'فقط تفاوت‌هایی را نگه دار که روی استفاده واقعی اثر دارند.'}];
export const getBrand=(x)=>brands.find((b)=>b.id===x||b.slug===x);
export const getSeries=(x)=>series.find((s)=>s.id===x||s.slug===x);
export const getModel=(x)=>models.find((m)=>m.id===x||m.slug===x);
export const getProduct=(x)=>products.find((p)=>p.id===x||p.slug===x);
export const productsForModel=(id)=>products.filter((p)=>p.modelId===id);
export const variantsForModel=(id)=>variants.filter((v)=>v.modelId===id);
